name: Sync to Drive
on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rclone
        uses: rclone/rclone-action@v1
        with:
          config-data: ${{ secrets.RCLONE_CONFIG_DATA }}

      - name: Rclone Sync
        run: |
          rclone sync . gdrive: -v --drive-use-trash